version: '3.7'
services:
  rabbit:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: "localhost"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
    driver: local
